export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PROFILE_PICTURE = "CHANGE_PROFILE_PICTURE";

// master role
export const GET_ROLE = "GET_ROLE";
export const CREATE_ROLE = "CREATE_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
export const EXPORT_ROLE = "EXPORT_ROLE";

// master menu access
export const GET_MENU_ACCESS = "GET_MENU_ACCESS";
export const SAVE_MENU_ACCESS = "SAVE_MENU_ACCESS";
export const EXPORT_MENU_ACCESS = "EXPORT_MENU_ACCESS";

// log activity
export const GET_LOG_ACTIVITY = "GET_LOG_ACTIVITY";
export const DELETE_LOG_ACTIVITY_BY_ID = "DELETE_LOG_ACTIVITY_BY_ID";
export const DELETE_LOG_ACTIVITY_FILTER = "DELETE_LOG_ACTIVITY_FILTER";
export const DOWNLOAD_ACTIVITY_BY_ID = "DOWNLOAD_ACTIVITY_BY_ID";
export const DOWNLOAD_ACTIVITY_FILTER = "DOWNLOAD_ACTIVITY_FILTER";

// log notification
export const GET_LOG_NOTIFICATION = 'GET_LOG_NOTIFICATION'
export const DELETE_LOG_NOTIFICATION_BY_ID = 'DELETE_LOG_NOTIFICATION_BY_ID'
export const DELETE_LOG_NOTIFICATION_FILTER = 'DELETE_LOG_NOTIFICATION_FILTER'
export const DOWNLOAD_NOTIFICATION_BY_ID = 'DOWNLOAD_NOTIFICATION_BY_ID'
export const DOWNLOAD_NOTIFICATION_FILTER = 'DOWNLOAD_NOTIFICATION_FILTER'

// system update
export const GET_SYSTEM_UPDATE = "GET_SYSTEM_UPDATE";

// notifications
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_UNREAD_NOTIFICATIONS = "GET_UNREAD_NOTIFICATIONS";
export const READ_NOTIFICATIONS = "READ_NOTIFICATIONS";
export const ALL_NOTIFICATIONS = "ALL_NOTIFICATIONS";

// master batch
export const GET_BATCH = "GET_BATCH";
export const GET_BATCH_DROPDOWN = "GET_BATCH_DROPDOWN";
export const GET_BATCH_FILTER = "GET_BATCH_FILTER";
export const CREATE_BATCH = "CREATE_BATCH";
export const UPDATE_BATCH = "UPDATE_BATCH";
export const UPDATE_STATUS_BATCH = "UPDATE_STATUS_BATCH";
export const DELETE_BATCH = "DELETE_BATCH";
export const EXPORT_BATCH = "EXPORT_BATCH";

// master category project
export const GET_CATEGORY_PROJECT = "GET_CATEGORY_PROJECT";
export const GET_CATEGORY_PROJECT_DROPDOWN = "GET_CATEGORY_PROJECT_DROPDOWN";
export const GET_CATEGORY_PROJECT_FILTER = "GET_CATEGORY_PROJECT_FILTER";
export const CREATE_CATEGORY_PROJECT = "CREATE_CATEGORY_PROJECT";
export const UPDATE_CATEGORY_PROJECT = "UPDATE_CATEGORY_PROJECT";
export const UPDATE_STATUS_CATEGORY_PROJECT = "UPDATE_STATUS_CATEGORY_PROJECT";
export const DELETE_CATEGORY_PROJECT = "DELETE_CATEGORY_PROJECT";
export const EXPORT_CATEGORY_PROJECT = "EXPORT_CATEGORY_PROJECT";

// master status project
export const GET_STATUS_PROJECT = "GET_STATUS_PROJECT";
export const GET_STATUS_PROJECT_DROPDOWN = "GET_STATUS_PROJECT_DROPDOWN";
export const GET_STATUS_PROJECT_FILTER = "GET_STATUS_PROJECT_FILTER";
export const CREATE_STATUS_PROJECT = "CREATE_STATUS_PROJECT";
export const UPDATE_STATUS_PROJECT = "UPDATE_STATUS_PROJECT";
export const UPDATE_STATUS_STATUS_PROJECT = "UPDATE_STATUS_STATUS_PROJECT";
export const DELETE_STATUS_PROJECT = "DELETE_STATUS_PROJECT";
export const EXPORT_STATUS_PROJECT = "EXPORT_STATUS_PROJECT";

// master mitra
export const GET_MITRA = "GET_MITRA";
export const GET_MITRA_DROPDOWN = "GET_MITRA_DROPDOWN";
export const GET_MITRA_FILTER = "GET_MITRA_FILTER";
export const CREATE_MITRA = "CREATE_MITRA";
export const UPDATE_MITRA = "UPDATE_MITRA";
export const UPDATE_STATUS_MITRA = "UPDATE_STATUS_MITRA";
export const DELETE_MITRA = "DELETE_MITRA";
export const EXPORT_MITRA = "EXPORT_MITRA";

// master REGIONAL
export const GET_REGIONAL = "GET_REGIONAL";
export const GET_REGIONAL_DROPDOWN = "GET_REGIONAL_DROPDOWN";
export const GET_REGIONAL_FILTER = "GET_REGIONAL_FILTER";
export const CREATE_REGIONAL = "CREATE_REGIONAL";
export const UPDATE_REGIONAL = "UPDATE_REGIONAL";
export const UPDATE_STATUS_REGIONAL = "UPDATE_STATUS_REGIONAL";
export const DELETE_REGIONAL = "DELETE_REGIONAL";
export const EXPORT_REGIONAL = "EXPORT_REGIONAL";

// master AREA
export const GET_AREA = "GET_AREA";
export const GET_AREA_DROPDOWN = "GET_AREA_DROPDOWN";
export const GET_AREA_FILTER = "GET_AREA_FILTER";
export const CREATE_AREA = "CREATE_AREA";
export const UPDATE_AREA = "UPDATE_AREA";
export const UPDATE_STATUS_AREA = "UPDATE_STATUS_AREA";
export const DELETE_AREA = "DELETE_AREA";
export const EXPORT_AREA = "EXPORT_AREA";

// master BRANCH
export const GET_BRANCH = "GET_BRANCH";
export const GET_BRANCH_DROPDOWN = "GET_BRANCH_DROPDOWN";
export const GET_BRANCH_FILTER = "GET_BRANCH_FILTER";
export const CREATE_BRANCH = "CREATE_BRANCH";
export const UPDATE_BRANCH = "UPDATE_BRANCH";
export const UPDATE_STATUS_BRANCH = "UPDATE_STATUS_BRANCH";
export const DELETE_BRANCH = "DELETE_BRANCH";
export const EXPORT_BRANCH = "EXPORT_BRANCH";

// master STO
export const GET_STO = "GET_STO";
export const GET_STO_DROPDOWN = "GET_STO_DROPDOWN";
export const GET_STO_FILTER = "GET_STO_FILTER";
export const CREATE_STO = "CREATE_STO";
export const UPDATE_STO = "UPDATE_STO";
export const UPDATE_STATUS_STO = "UPDATE_STATUS_STO";
export const DELETE_STO = "DELETE_STO";
export const EXPORT_STO = "EXPORT_STO";