export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const CHANGE_PROFILE_PICTURE = 'CHANGE_PROFILE_PICTURE'

// master role
export const GET_ROLE = 'GET_ROLE'
export const CREATE_ROLE = 'CREATE_ROLE'
export const UPDATE_ROLE = 'UPDATE_ROLE'
export const DELETE_ROLE = 'DELETE_ROLE'
export const EXPORT_ROLE = 'EXPORT_ROLE'

// master menu access
export const GET_MENU_ACCESS = 'GET_MENU_ACCESS'
export const SAVE_MENU_ACCESS = 'SAVE_MENU_ACCESS'
export const EXPORT_MENU_ACCESS = 'EXPORT_MENU_ACCESS'

// master user
export const GET_MASTER_USER = 'GET_MASTER_USER'
export const CREATE_MASTER_USER = 'CREATE_MASTER_USER'
export const UPDATE_MASTER_USER = 'UPDATE_MASTER_USER'
export const DELETE_MASTER_USER = 'DELETE_MASTER_USER'
export const EXPORT_MASTER_USER = 'EXPORT_MASTER_USER'

// setting latest feature
export const GET_SETTING_LATEST_FEATURE = 'GET_SETTING_LATEST_FEATURE'
export const CREATE_SETTING_LATEST_FEATURE = 'CREATE_SETTING_LATEST_FEATURE'
export const UPDATE_SETTING_LATEST_FEATURE = 'UPDATE_SETTING_LATEST_FEATURE'
export const DELETE_SETTING_LATEST_FEATURE = 'DELETE_SETTING_LATEST_FEATURE'
export const EXPORT_SETTING_LATEST_FEATURE = 'EXPORT_SETTING_LATEST_FEATURE'

// log activity
export const GET_LOG_ACTIVITY = 'GET_LOG_ACTIVITY'
export const DELETE_LOG_ACTIVITY_BY_ID = 'DELETE_LOG_ACTIVITY_BY_ID'
export const DELETE_LOG_ACTIVITY_FILTER = 'DELETE_LOG_ACTIVITY_FILTER'
export const DOWNLOAD_ACTIVITY_BY_ID = 'DOWNLOAD_ACTIVITY_BY_ID'
export const DOWNLOAD_ACTIVITY_FILTER = 'DOWNLOAD_ACTIVITY_FILTER'

// system update
export const GET_SYSTEM_UPDATE = 'GET_SYSTEM_UPDATE'

// notifications
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const GET_UNREAD_NOTIFICATIONS = 'GET_UNREAD_NOTIFICATIONS'
export const READ_NOTIFICATIONS = 'READ_NOTIFICATIONS'
export const ALL_NOTIFICATIONS = 'ALL_NOTIFICATIONS'

// master colorway
export const GET_DROPDOWN_DATA_COLORWAY = 'GET_DROPDOWN_DATA_COLORWAY'
export const GET_DATA_COLORWAY = 'GET_DATA_COLORWAY'
export const CREATE_COLORWAY = 'CREATE_COLORWAY'
export const DELETE_COLORWAY = 'DELETE_COLORWAY'
export const UPDATE_COLORWAY = 'UPDATE_COLORWAY'
export const DOWNLOAD_TEMPLATE_COLORWAY = 'DOWNLOAD_TEMPLATE_COLORWAY'
export const EXPORT_COLORWAY = 'EXPORT_COLORWAY'
export const UPLOAD_COLORWAY = 'UPLOAD_COLORWAY'
export const INSERT_FILE_UPLOAD_COLORWAY = 'INSERT_FILE_UPLOAD_COLORWAY'

